Repository medizininformatik-initiative/INTERPOLAR, pull requests merged in 2024-02, with the labels that each got.

#66 64 kds2db datenbankzugriffsdaten für alle module in eine separate db configtoml verschieben
  R-kds2db/kds2db/NAMESPACE
  R-kds2db/kds2db/R/00_Main.R
  R-kds2db/kds2db/R/04_Write_Tables_To_Database.R
  R-kds2db/kds2db/man/writeResourceTablesToDatabase.Rd
  R-kds2db/kds2db/man/writeTablesToDatabase.Rd
  R-kds2db/kds2db_config.toml
  R-mrputils/mrputils/NAMESPACE
  R-mrputils/mrputils/R/lib_db.R
  R-mrputils/mrputils/man/addDatabaseInternalColumns.Rd
  R-mrputils/mrputils/man/addTableContentToDatabase.Rd
  R-mrputils/mrputils/man/dbAddContent.Rd
  R-mrputils/mrputils/man/dbConnect.Rd
  R-mrputils/mrputils/man/dbDeleteContent.Rd
  R-mrputils/mrputils/man/dbDisconnect.Rd
  R-mrputils/mrputils/man/dbListTables.Rd
  R-mrputils/mrputils/man/deleteTableContentFromDatabase.Rd
  R-mrputils/mrputils/man/getDBConnection.Rd
  R-mrputils/mrputils/man/showTablesStructure.Rd
  mrp_db_config.toml
Labels: enhancement

#70 69 db benennung initialer commit
  .dockerignore
  Postgres-amts_db/build/Dockerfile
  Postgres-amts_db/init/init-db.sql
  Postgres-amts_db/postgresql.conf
  Postgres-amts_db/template_env_amts_db.password
  docker-compose.yml
Labels: enhancement

#74 73 initiale einrichtung docker auf der vm
  .gitignore
  R-etlutils/Dockerfile
  R-kds2db/Dockerfile
  R-kds2db/kds2db/R/00_Main.R
  R-kds2db/kds2db_config.toml
  amts_db_config.toml
  docker-compose.yml
Labels: enhancement

#78 77 finalisierende arbeiten docker compose setup
  docker-compose.yml
Labels: enhancement

#82 29 skript zum daten in redcap schicken
  .gitignore
  R-db2frontend/StartDB2Frontend.R
  R-db2frontend/db2frontend/.Rbuildignore
  R-db2frontend/db2frontend/.gitignore
  R-db2frontend/db2frontend/DESCRIPTION
  R-db2frontend/db2frontend/LICENSE.md
  R-db2frontend/db2frontend/NAMESPACE
  R-db2frontend/db2frontend/R/dbDatatoREDCap.R
  R-db2frontend/db2frontend/db2frontend.Rproj
  R-db2frontend/db2frontend/man/copyDB2Redcap.Rd
  R-db2frontend/db2frontend/man/initConstants.Rd
  R-db2frontend/db2frontend_config.toml
  REDCap-frontend/Fall.zip
  REDCap-frontend/INTERPOLARDev_DataDictionary.xlsx
  REDCap-frontend/MRPDokumentationValidation.zip
  REDCap-frontend/Medikationsanalyse.zip
  REDCap-frontend/Patient.zip
Labels: enhancement

#87 85 kds2db definition der table description erleichtern
  R-etlutils/etlutils/NAMESPACE
  R-etlutils/etlutils/R/lib_helper_functions.R
  R-etlutils/etlutils/R/lib_table.R
  R-etlutils/etlutils/inst/extdata/test_excel_file.xlsx
  R-etlutils/etlutils/man/isSimpleNotEmptyString.Rd
  R-etlutils/etlutils/man/moveColumnBefore.Rd
  R-etlutils/etlutils/man/removeRowsWithNAorEmpty.Rd
  R-etlutils/etlutils/man/replacePatternsInColumn.Rd
  R-etlutils/etlutils/man/replacePatternsInString.Rd
  R-etlutils/etlutils/man/splitColumnToRows.Rd
  R-etlutils/etlutils/man/trimTableValues.Rd
  R-etlutils/etlutils/man/writeExcelFile.Rd
  R-etlutils/etlutils/tests/testthat/test-lib_helper_functions.R
  R-etlutils/etlutils/tests/testthat/test-lib_table.R
  R-kds2db/kds2db/NAMESPACE
  R-kds2db/kds2db/R/Preparation_Expand_TableDescription.R
  R-kds2db/kds2db/inst/extdata/Table_Description.xlsx
  R-kds2db/kds2db/inst/extdata/Table_Description_Definition.xlsx
  R-kds2db/kds2db/man/expandTableDescription.Rd
  R-kds2db/kds2db/man/expandTableDescriptionFromFile.Rd
  R-kds2db/kds2db/man/expandTableDescriptionInternal.Rd
  R-kds2db/kds2db/man/extractReplacePatterns.Rd
  R-kds2db/kds2db/tests/testthat/test-DUMMY_TESTFILE.R
  R-kds2db/kds2db/tests/testthat/test-Preparation_Expand_TableDescription.R
Labels: enhancement

#89 88 kds2db update table description
  R-etlutils/etlutils/man/addCharlsonScore.Rd
  R-kds2db/kds2db/R/Preparation_Expand_TableDescription.R
  R-kds2db/kds2db/inst/extdata/Table_Description.xlsx
  R-kds2db/kds2db/inst/extdata/Table_Description_Definition.xlsx
Labels: bug, enhancement

#95 92 kds2db fehlerbehebung beim logging und in der table description
  R-etlutils/etlutils/NAMESPACE
  R-etlutils/etlutils/R/lib_misc.R
  R-etlutils/etlutils/R/lib_sample_resources.R
  R-etlutils/etlutils/man/END__.Rd
  R-etlutils/etlutils/man/END__START__.Rd
  R-etlutils/etlutils/man/START__.Rd
  R-etlutils/etlutils/man/log_run.Rd
  R-etlutils/etlutils/man/polar_download_by_ids_and_crack_parallel.Rd
  R-kds2db/kds2db/NAMESPACE
  R-kds2db/kds2db/R/00_Main.R
  R-kds2db/kds2db/R/Preparation_Expand_TableDescription.R
  R-kds2db/kds2db/inst/extdata/Table_Description.xlsx
  R-kds2db/kds2db/inst/extdata/Table_Description_Definition.xlsx
  R-kds2db/kds2db/man/checkResult.Rd
Labels: bug, enhancement

#99 Change build of R environment from multiple Dockerfiles to a single D…
  Dockerfile_R
  R-db2frontend/Dockerfile
  R-etlutils/Dockerfile
  R-kds2db/Dockerfile
  README.md
  docker-compose.yml
Labels: enhancement

#100 Release
  Dockerfile_R
  R-db2frontend/Dockerfile
  R-etlutils/Dockerfile
  R-kds2db/Dockerfile
  README.md
  docker-compose.yml
Labels: enhancement

#104 kds2db korrektes arbeitsverzeichnis setzen
  R-etlutils/etlutils/DESCRIPTION
  R-etlutils/etlutils/NAMESPACE
  R-etlutils/etlutils/R/global_variables.R
  R-etlutils/etlutils/R/lib_colourise_text.R
  R-etlutils/etlutils/R/lib_db.R
  R-etlutils/etlutils/R/lib_dir.R
  R-etlutils/etlutils/R/lib_helper_functions.R
  R-etlutils/etlutils/R/lib_logging.R
  R-etlutils/etlutils/R/lib_misc.R
  R-etlutils/etlutils/R/lib_sample_resources.R
  R-etlutils/etlutils/R/lib_table.R
  R-etlutils/etlutils/R/retrieve_encounter.R
  R-etlutils/etlutils/man/END__.Rd
  R-etlutils/etlutils/man/END__START__.Rd
  R-etlutils/etlutils/man/START__.Rd
  R-etlutils/etlutils/man/cat_headline.Rd
  R-etlutils/etlutils/man/cat_white.Rd
  R-etlutils/etlutils/man/check_error.Rd
  R-etlutils/etlutils/man/complete_table.Rd
  R-etlutils/etlutils/man/convertDateInformation.Rd
  R-etlutils/etlutils/man/convertTimeToPOSIXct.Rd
  R-etlutils/etlutils/man/dataTableAsCharacter.Rd
  R-etlutils/etlutils/man/fhir_url_add_common_request_params.Rd
  R-etlutils/etlutils/man/fixDateFormat.Rd
  R-etlutils/etlutils/man/frame_string.Rd
  R-etlutils/etlutils/man/get_pattern_YYYY.Rd
  R-etlutils/etlutils/man/get_pattern_YYYY_MM.Rd
  R-etlutils/etlutils/man/log_run.Rd
  R-etlutils/etlutils/man/plural_s.Rd
  R-etlutils/etlutils/man/polar_disclaimer.Rd
  R-etlutils/etlutils/man/polar_get_resources_by_ids.Rd
  R-etlutils/etlutils/man/print_table_summary.Rd
  R-etlutils/etlutils/man/run.Rd
  R-etlutils/etlutils/man/runProcess.Rd
  R-etlutils/etlutils/man/run_in.Rd
  R-etlutils/etlutils/man/run_in_in.Rd
  R-etlutils/etlutils/man/run_in_in_ignore_error.Rd
  R-etlutils/etlutils/man/run_out.Rd
  R-etlutils/etlutils/man/runs.Rd
  R-etlutils/etlutils/man/runs_in.Rd
  R-etlutils/etlutils/man/runs_in_in.Rd
  R-etlutils/etlutils/man/runs_out.Rd
  R-etlutils/etlutils/man/save_performance.Rd
  R-etlutils/etlutils/man/verbose_numbers.Rd
  R-etlutils/etlutils/tests/testthat/test-lib_helper_functions.R
  R-etlutils/etlutils/tests/testthat/test-lib_misc.R
  R-kds2db/StartRetrieval.R
  R-kds2db/kds2db/R/00_Main.R
  R-kds2db/kds2db/R/04_Write_Tables_To_Database.R
Labels: bug

#106 105 kds2db pfade für toml dateien korrigieren
  R-etlutils/etlutils/R/lib_helper_functions.R
  R-kds2db/kds2db/R/00_Main.R
Labels: bug, documentation

#107 84 redcap deploy variante 1 ip redcap from redcap plain download
  Dockerfile_R
  REDCap-app/html/Readme.md
  REDCap-db/init/redcap.sql
  REDCap-db/mariadb.cnf
  docker-compose.yml
Labels: enhancement

#110 106 db2frontend pfade für toml dateien korrigieren
  R-db2frontend/db2frontend/R/dbDatatoREDCap.R
Labels: bug

#111 DB update init script with new tables
  Postgres-amts_db/init/init-db.sql
Labels: bug

#113 U Fix missing URL_PORT_SPEC variable
  R-etlutils/etlutils/R/lib_helper_functions.R
Labels: bug

#115 DB fix script
  Postgres-amts_db/init/init-db.sql
Labels: bug

#116 112 ksd2db verbesserung des loggings
  R-etlutils/etlutils/NAMESPACE
  R-etlutils/etlutils/R/lib_clock.R
  R-etlutils/etlutils/R/lib_db.R
  R-etlutils/etlutils/R/lib_helper_functions.R
  R-etlutils/etlutils/man/stopOnError.Rd
  R-kds2db/kds2db/R/00_Main.R
  R-kds2db/kds2db/R/01_Get_PIDs.R
Labels: bug, documentation

#117 DB change itemnames
  Postgres-amts_db/init/init-db.sql
Labels: bug

#119 DB bigger med_code_system varchar
  Postgres-amts_db/init/init-db.sql
Labels: bug

#122 P Create initial DataProcessor project
  R-dataprocessor/dataprocessor/.Rbuildignore
  R-dataprocessor/dataprocessor/.gitignore
  R-dataprocessor/dataprocessor/DESCRIPTION
  R-dataprocessor/dataprocessor/LICENSE.md
  R-dataprocessor/dataprocessor/NAMESPACE
  R-dataprocessor/dataprocessor/dataprocessor.Rproj
  R-dataprocessor/dataprocessor/tests/testthat.R
  R-dataprocessor/dataprocessor/tests/testthat/test-DUMMY-TEST.R
Labels: enhancement

#125 120 redcap api token und url in db2frontend configtoml
  R-db2frontend/StartDB2Frontend.R
  R-db2frontend/db2frontend/R/dbDatatoREDCap.R
  R-db2frontend/db2frontend_config.toml
Labels: bug, enhancement

#128 124 kds2db update table description
  R-kds2db/kds2db/R/Preparation_Expand_TableDescription.R
  R-kds2db/kds2db/inst/extdata/Table_Description.xlsx
  R-kds2db/kds2db/inst/extdata/Table_Description_Definition.xlsx
  R-kds2db/kds2db/man/addEmptyRowsBeforeNewResource.Rd
  R-kds2db/kds2db/tests/testthat/test-Preparation_Expand_TableDescription.R
Labels: bug

#129 126 kds2db kleine anpassungen für release v01
  R-etlutils/etlutils/R/lib_helper_functions.R
  R-etlutils/etlutils/R/lib_sample_resources.R
  R-etlutils/etlutils/man/polar_download_by_ids_and_crack_parallel.Rd
  R-etlutils/etlutils/man/stopOnError.Rd
  R-kds2db/README.md
  R-kds2db/kds2db_config.toml
Labels: documentation

#131 130 add pids per ward in table description
  R-kds2db/kds2db/R/Preparation_Expand_TableDescription.R
  R-kds2db/kds2db/inst/extdata/Table_Description.xlsx
  R-kds2db/kds2db/inst/extdata/Table_Description_Definition.xlsx
Labels: bug

#133 132 kds2db automatische generierung des initialen sql skriptes
  Postgres-amts_db/init/init-db.sql
  Postgres-amts_db/init/init-db_template.sql
  Postgres-amts_db/init/init-db_template_sub_grant.sql
  R-kds2db/kds2db/R/Preparation_Create_TableStatements.R
  R-kds2db/kds2db/inst/extdata/Table_Description.xlsx
  R-kds2db/kds2db/inst/extdata/Table_Description_Definition.xlsx
Labels: enhancement

#134 84 redcap deploy variante 1 ip redcap from redcap plain download
  Install.md
  README.md
  REDCap-app/Readme.md
  REDCap-app/html/Readme.md
  REDCap-db/mariadb.cnf
Labels: documentation

#136 135 kds2db letzte fehlerbehebungen vor release v01
  R-etlutils/etlutils/man/polar_download_by_ids_and_crack_parallel.Rd
  R-kds2db/kds2db/R/Preparation_Create_TableStatements.R
Labels: bug

#139 K + DB Move template SQL Scripts to subfolder 'template'
  Postgres-amts_db/init/template/init-db_template.sql
  Postgres-amts_db/init/template/init-db_template_sub_grant.sql
  R-etlutils/etlutils/NAMESPACE
  R-etlutils/etlutils/R/lib_colourise_text.R
  R-etlutils/etlutils/R/lib_helper_functions.R
  R-etlutils/etlutils/R/lib_sample_resources.R
  R-etlutils/etlutils/R/lib_table.R
  R-etlutils/etlutils/R/retrieve_encounter.R
  R-etlutils/etlutils/man/cat_brown.Rd
  R-etlutils/etlutils/man/cat_cyan.Rd
  R-etlutils/etlutils/man/cat_error.Rd
  R-etlutils/etlutils/man/cat_info.Rd
  R-etlutils/etlutils/man/cat_warning.Rd
  R-etlutils/etlutils/man/cat_yellow.Rd
  R-etlutils/etlutils/man/print_table.Rd
  R-etlutils/etlutils/man/print_table_if_all.Rd
  R-etlutils/etlutils/man/print_table_summary.Rd
  R-kds2db/kds2db/R/03_Load_Resources.R
  R-kds2db/kds2db/R/Preparation_Create_TableStatements.R
  R-kds2db/kds2db/R/Preparation_Expand_TableDescription.R
  R-kds2db/kds2db/inst/extdata/Table_Description.xlsx
Labels: bug
